import * as vscode from "vscode";
import { telemetry } from "../telemetry";

export class OutputFormatter {
    public static getDiagramFileContent(modelName: string, llmResponse: string): string {
        let eraserBlock = this.getEraserBlock(llmResponse);
        let eraserCode = eraserBlock.replace(/```eraser|```/g, "").trim();

        return `# 🏗️ Architecture Diagram

<div align="center">

[![Swark](https://raw.githubusercontent.com/swark-io/swark/refs/heads/main/assets/logo/swark-logo-dark-mode.png)](https://swark.io)

**Automatic Architecture Diagrams from Code**  
[GitHub](https://github.com/swark-io/swark) • [Website](https://swark.io) • [Contact](mailto:contact@swark.io)

</div>

---

## � Diagram Information

| **Property** | **Value** |
|--------------|-----------|
| **Generated by** | ${modelName} |
| **Timestamp** | ${new Date().toLocaleString()} |
| **Format** | Eraser.io Cloud Architecture |

---

## 🚀 Quick Actions

<div align="center">

### [🎨 **Open in Eraser Workspace**](https://app.eraser.io/workspace/qaNiop5qECxiRnMwgmYj/new?template=cloud-architecture&code=${encodeURIComponent(eraserCode)})
*Click to automatically create and edit your diagram online*

### [⚙️ **Change Language Model**](vscode://settings/swark.eraser.languageModel)
*Switch to a different AI model for better results*

</div>

---

## 📐 Generated Diagram

\`\`\`eraser
${eraserCode}
\`\`\`

---

## 📖 How to Use

### ✨ Quick Start (Recommended)
1. **Click the Eraser Workspace link above** → Instantly opens with your diagram ready to edit
2. **Customize visually** → Add colors, rearrange components, modify layout
3. **Export & Share** → Download as PNG, SVG, or share with your team

### 🔧 Advanced Options
- **Better AI Models**: Try \`claude-3.5-sonnet\` for more complex architectures
- **Iterate**: Generate multiple times to get the best result
- **Integration**: Embed diagrams in documentation or presentations

### 💡 Pro Tips
- **Real-time Collaboration**: Share workspace link for team editing
- **Version Control**: Export diagrams to track architecture evolution  
- **Professional Formats**: Use for technical documentation and presentations

---

<div align="center">
<em>Generated by Swark - Bringing your code architecture to life</em>
</div>
`;
    }

    public static getEraserBlock(llmResponse: string): string {
        // Try to find Eraser code block first
        let matches = llmResponse.match(/```eraser[\s\S]*?```/);
        
        if (!matches) {
            // Try generic code block
            matches = llmResponse.match(/```[\s\S]*?```/);
        }

        if (!matches) {
            // If no code block found, check if response looks like raw Eraser syntax
            const cleanResponse = llmResponse.trim();
            if (cleanResponse.includes('title ') || cleanResponse.includes('[icon:') || cleanResponse.includes('] {')) {
                return cleanResponse;
            }
            throw new Error("No Eraser block found in the language model response. Please try again.");
        }

        const block = matches[0];

        if (block !== llmResponse.trim()) {
            telemetry.sendTelemetryEvent("llmResponseContainedExtraPayload");
        }

        return block;
    }

    private static convertEraserToMermaidPreview(eraserCode: string): string {
        try {
            // Parse the Eraser code and convert to a simplified Mermaid diagram
            const lines = eraserCode.split('\n').map(line => line.trim()).filter(line => line);
            let mermaid = 'graph TD\n';
            let nodeId = 0;
            const nodeMap = new Map<string, string>();
            
            // Extract title
            const titleLine = lines.find(line => line.startsWith('title '));
            if (titleLine) {
                const title = titleLine.replace('title ', '').trim();
                mermaid += `    subgraph "${title}"\n`;
            }
            
            // Process layers and components
            for (let i = 0; i < lines.length; i++) {
                const line = lines[i];
                
                // Layer definition
                if (line.includes('[icon:') && line.includes('{')) {
                    const layerName = line.split('[')[0].trim();
                    const layerId = `L${nodeId++}`;
                    nodeMap.set(layerName, layerId);
                    mermaid += `        ${layerId}["🏗️ ${layerName}"]\n`;
                }
                
                // Component definition (inside layers)
                else if (line.includes('[icon:') && line.includes('label:')) {
                    const componentName = line.split('[')[0].trim();
                    const labelMatch = line.match(/label:\s*"([^"]+)"/);
                    const label = labelMatch ? labelMatch[1] : componentName;
                    const componentId = `C${nodeId++}`;
                    nodeMap.set(componentName, componentId);
                    mermaid += `        ${componentId}["${componentName}<br/><small>${label}</small>"]\n`;
                }
                
                // Connection
                else if (line.includes('>') && !line.startsWith('//')) {
                    const parts = line.split('>').map(p => p.trim());
                    if (parts.length === 2) {
                        const fromId = nodeMap.get(parts[0]);
                        const toId = nodeMap.get(parts[1]);
                        if (fromId && toId) {
                            mermaid += `        ${fromId} --> ${toId}\n`;
                        }
                    }
                }
            }
            
            if (titleLine) {
                mermaid += '    end\n';
            }
            
            // Add some styling
            mermaid += '\n    classDef layerClass fill:#e1f5fe,stroke:#01579b,stroke-width:2px\n';
            mermaid += '    classDef componentClass fill:#f3e5f5,stroke:#4a148c,stroke-width:1px\n';
            
            return mermaid;
        } catch (error) {
            console.error("Error converting Eraser to Mermaid preview:", error);
            return `graph TD
    A["📋 Architecture Diagram Generated"]
    B["🎨 Preview Error - Check Eraser Code Below"]
    A --> B
    style A fill:#e1f5fe
    style B fill:#ffebee`;
        }
    }

    public static getLogFileContent(
        selectedFolder: vscode.Uri,
        model: vscode.LanguageModelChat,
        filePaths: string[]
    ): string {
        const timestamp = new Date().toLocaleString();
        const json = JSON.stringify(
            {
                selectedFolder: selectedFolder.fsPath,
                model: { family: model.family, name: model.name, maxInputTokens: model.maxInputTokens },
                numFilesUsed: filePaths.length,
                timestamp: timestamp
            },
            null,
            4
        );

        return `# 📊 Swark Generation Log

<div align="center">

**Architecture Diagram Generation Report**  
*Generated on ${timestamp}*

</div>

---

## 🔧 Configuration

| **Setting** | **Value** |
|-------------|-----------|
| **Model Family** | ${model.family} |
| **Model Name** | ${model.name} |
| **Max Input Tokens** | ${model.maxInputTokens?.toLocaleString() || 'Unknown'} |
| **Source Folder** | \`${selectedFolder.fsPath}\` |
| **Files Processed** | **${filePaths.length}** files |

---

## 📁 Processed Files

<details>
<summary><strong>Click to view all ${filePaths.length} files</strong></summary>

\`\`\`
${filePaths.map((path, index) => `${(index + 1).toString().padStart(3, ' ')}. ${path}`).join('\n')}
\`\`\`

</details>

---

## 🔧 Raw Configuration Data

<details>
<summary><strong>Click to view JSON configuration</strong></summary>

\`\`\`json
${json}
\`\`\`

</details>

---

<div align="center">
<em>Log generated by Swark Eraser Extension</em>
</div>
`;
    }
}
