graph TD
    index.ts --> express
    index.ts --> cors
    index.ts --> src/user/router
    index.ts --> src/user/middleware/error-handler
    index.ts --> src/user/middleware/response-structure
    index.ts --> dotenv
    src\user\router.ts --> express
    src\user\router.ts --> controller/auth-contoller/signup
    src\user\router.ts --> controller/auth-contoller/login
    src\user\router.ts --> controller/blog-controller/get
    src\user\router.ts --> controller/blog-controller/get-by-id
    src\user\router.ts --> controller/blog-controller/post
    src\user\router.ts --> controller/blog-controller/put
    src\user\router.ts --> controller/blog-controller/delete
    src\user\router.ts --> controller/blog-controller/like
    src\user\router.ts --> controller/blog-controller/dislike
    src\user\router.ts --> controller/blog-controller/add-cmnt
    src\user\router.ts --> controller/blog-controller/get-cmnt
    src\user\router.ts --> controller/blog-controller/delete-cmnt
    src\user\router.ts --> controller/blog-controller/sort-blog
    src\user\router.ts --> controller/blog-controller/filter-blog
    src\user\router.ts --> middleware/authenticateUser
    src\user\router.ts --> middleware/author-middlware
    src\user\router.ts --> middleware/writer-middleware
    src\user\router.ts --> .user/utils/validation-schema/user-schema
    src\user\router.ts --> .user/utils/validation-schema/create-blog-schema
    src\user\router.ts --> .user/utils/validation-schema/update-blog-schema
    src\user\controller\auth-contoller\login.ts --> ..utils/db
    src\user\controller\auth-contoller\login.ts --> ..utils/customError
    src\user\controller\auth-contoller\login.ts --> ..utils/jwt
    src\user\controller\auth-contoller\login.ts --> ..utils/password
    src\user\controller\auth-contoller\login.ts --> express
    src\user\controller\auth-contoller\signup.ts --> ..utils/db
    src\user\controller\auth-contoller\signup.ts --> dotenv
    src\user\controller\auth-contoller\signup.ts --> ..utils/customError
    src\user\controller\auth-contoller\signup.ts --> ..utils/password
    src\user\controller\auth-contoller\signup.ts --> express
    src\user\controller\blog-controller\add-cmnt.ts --> ..utils/db
    src\user\controller\blog-controller\add-cmnt.ts --> ..utils/customError
    src\user\controller\blog-controller\add-cmnt.ts --> express
    src\user\controller\blog-controller\delete-cmnt.ts --> ..utils/db
    src\user\controller\blog-controller\delete-cmnt.ts --> ..utils/customError
    src\user\controller\blog-controller\delete-cmnt.ts --> express
    src\user\controller\blog-controller\delete.ts --> ..utils/db
    src\user\controller\blog-controller\delete.ts --> ..utils/customError
    src\user\controller\blog-controller\delete.ts --> express
    src\user\controller\blog-controller\dislike.ts --> ..utils/db
    src\user\controller\blog-controller\dislike.ts --> ..utils/customError
    src\user\controller\blog-controller\dislike.ts --> uuid
    src\user\controller\blog-controller\dislike.ts --> express
    src\user\controller\blog-controller\filter-blog.ts --> ..utils/db
    src\user\controller\blog-controller\filter-blog.ts --> ..utils/customError
    src\user\controller\blog-controller\filter-blog.ts --> express
    src\user\controller\blog-controller\get-by-id.ts --> ..utils/db
    src\user\controller\blog-controller\get-by-id.ts --> ..utils/customError
    src\user\controller\blog-controller\get-by-id.ts --> express
    src\user\controller\blog-controller\get-cmnt.ts --> ..utils/db
    src\user\controller\blog-controller\get-cmnt.ts --> express
    src\user\controller\blog-controller\get.ts --> ..utils/db
    src\user\controller\blog-controller\get.ts --> ..utils/customError
    src\user\controller\blog-controller\get.ts --> express
    src\user\controller\blog-controller\like.ts --> ..utils/db
    src\user\controller\blog-controller\like.ts --> ..utils/customError
    src\user\controller\blog-controller\like.ts --> uuid
    src\user\controller\blog-controller\like.ts --> express
    src\user\controller\blog-controller\post.ts --> ..utils/db
    src\user\controller\blog-controller\post.ts --> ..utils/customError
    src\user\controller\blog-controller\post.ts --> express
    src\user\controller\blog-controller\put.ts --> ..utils/db
    src\user\controller\blog-controller\put.ts --> ..utils/customError
    src\user\controller\blog-controller\put.ts --> express
    src\user\controller\blog-controller\sort-blog.ts --> ..utils/db
    src\user\controller\blog-controller\sort-blog.ts --> ..utils/customError
    src\user\controller\blog-controller\sort-blog.ts --> express
    src\user\middleware\authenticateUser.ts --> express
    src\user\middleware\authenticateUser.ts --> .utils/jwt
    src\user\middleware\authenticateUser.ts --> .utils/customError
    src\user\middleware\author-middlware.ts --> .utils/db
    src\user\middleware\author-middlware.ts --> express
    src\user\middleware\author-middlware.ts --> .utils/customError
    src\user\middleware\error-handler.ts --> express
    src\user\middleware\response-structure.ts --> express
    src\user\middleware\validate-data.ts --> express
    src\user\middleware\validate-data.ts --> .utils/customError
    src\user\middleware\validate-data.ts --> joi
    src\user\middleware\writer-middleware.ts --> express
    src\user\middleware\writer-middleware.ts --> .utils/customError
    src\user\utils\db.ts --> mysql2/promise
    src\user\utils\jwt.ts --> jsonwebtoken
    src\user\utils\jwt.ts --> .utils/customError
    src\user\utils\password.ts --> bcrypt
    src\user\utils\validation-schema\create-blog-schema.ts --> ..middleware/validate-data
    src\user\utils\validation-schema\create-blog-schema.ts --> joi
    src\user\utils\validation-schema\update-blog-schema.ts --> ..middleware/validate-data
    src\user\utils\validation-schema\update-blog-schema.ts --> joi
    src\user\utils\validation-schema\user-schema.ts --> ..middleware/validate-data
    src\user\utils\validation-schema\user-schema.ts --> joi