FROM node:22-alpine as development

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# CMD ["npm", "run", "typeorm:migrate:generate"]

# CMD ["npm", "run", "typeorm:migrate:run"]

CMD ["npm", "run", "start:dev"]