FROM node:22-bullseye

# Install wkhtmltopdf + required fonts/libs
RUN apt-get update && apt-get install -y \
    wkhtmltopdf \
    fontconfig \
    libxrender1 \
    libxext6 \
    libjpeg62-turbo \
    xfonts-base \
    xfonts-75dpi \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8001
CMD ["npm", "run", "start:dev"]
